#!/bin/bash

function execute_download() {
  declare file_url="$1" file_sha256sum="$2" file_path="$3"

  echo "[installer] download ${file_url}"
  wget "${file_url}" -O "${file_path}" || exit 255
  chmod +x "${file_path}" || exit 255

  echo "${file_sha256sum} ${file_path}" | sha256sum -c - >/dev/null 2>&1
  if [[ $? -ne 0 ]]; then
    echo >&2 "Checksum verification failed for ${file_path}."
    exit 255
  fi

}

execute_download \
  'https://raw.githubusercontent.com/novln/Kiss-my-Arch/master/bootstrap/xps13-9380-install/bootstrap' \
  '52e972d65c292f9ea7808cb77698869b8209f471c44fc690576abadf606c59a5' \
  '/usr/local/sbin/arch-bootstrap'

execute_download \
  'https://raw.githubusercontent.com/novln/Kiss-my-Arch/master/bootstrap/xps13-9380-install/configure' \
  'da3382ed424d4d22b92ffba3bcf21d72670db48854e6a49e319cde3586e35b5b' \
  '/usr/local/sbin/arch-configure'

timedatectl set-ntp true

/usr/local/sbin/arch-bootstrap
if [[ $? -ne 0 ]]; then
  exit 254
fi

exit 0
