#!/bin/bash

function execute_download() {
  declare file_url="$1" file_sha256sum="$2" file_path="$3"

  echo "[installer] download ${file_url}"
  wget "${file_url}" -O "${file_path}" || exit 255
  chmod +x "${file_path}" || exit 255

  echo "${file_sha256sum} ${file_path}" | sha256sum -c - >/dev/null 2>&1
  if [[ $? -ne 0 ]]; then
    echo >&2 "Checksum verification failed for ${file_path}."
    exit 255
  fi

}

execute_download \
  'https://raw.githubusercontent.com/novln/Kiss-my-Arch/master/bootstrap/xps13-9333-install/bootstrap' \
  '34af8d30369aa2e7e0f19c518eaf180887d20df241ecbfd53ddd33af29af90b9' \
  '/usr/local/sbin/arch-bootstrap'

execute_download \
  'https://raw.githubusercontent.com/novln/Kiss-my-Arch/master/bootstrap/xps13-9333-install/configure' \
  'f77e74dc94da612368f3cb44cba42e0a8fd67264efe3bfb7600a667aeb48f671' \
  '/usr/local/sbin/arch-configure'

timedatectl set-ntp true

/usr/local/sbin/arch-bootstrap
if [[ $? -ne 0 ]]; then
  exit 254
fi

exit 0
