#!/bin/bash

function execute_download() {
  declare file_url="$1" file_sha256sum="$2" file_path="$3"

  echo "[installer] download ${file_url}"
  wget "${file_url}" -O "${file_path}" || exit 255
  chmod +x "${file_path}" || exit 255

  echo "${file_sha256sum} ${file_path}" | sha256sum -c - >/dev/null 2>&1
  if [[ $? -ne 0 ]]; then
    echo >&2 "Checksum verification failed for ${file_path}."
    exit 255
  fi

}

execute_download \
  'https://raw.githubusercontent.com/novln/Kiss-my-Arch/master/bootstrap/intel-nuc-8i3beh-install/bootstrap' \
  'dd4debbe3824b234f040924fc10ee107dfb2916be715a4ad32ecfa6ddb616f07' \
  '/usr/local/sbin/arch-bootstrap'

execute_download \
  'https://raw.githubusercontent.com/novln/Kiss-my-Arch/master/bootstrap/intel-nuc-8i3beh-install/configure' \
  '488de18fd8039806e9ed833c3ed1056ca15697d83946e6a1b0af498e29cffe17' \
  '/usr/local/sbin/arch-configure'

timedatectl set-ntp true

/usr/local/sbin/arch-bootstrap
if [[ $? -ne 0 ]]; then
  exit 254
fi

exit 0
