#!/bin/bash

function execute_download() {
  declare file_url="$1" file_sha256sum="$2" file_path="$3"

  echo "[installer] download ${file_url}"
  wget "${file_url}" -O "${file_path}" || exit 255
  chmod +x "${file_path}" || exit 255

  echo "${file_sha256sum} ${file_path}" | sha256sum -c - >/dev/null 2>&1
  if [[ $? -ne 0 ]]; then
    echo >&2 "Checksum verification failed for ${file_path}."
    exit 255
  fi

}

execute_download \
  'https://raw.githubusercontent.com/novln/Kiss-my-Arch/master/bootstrap/intel-nuc-8i3beh-install/bootstrap' \
  '50a48cc5509bc28759cb1a4adab654c9d0fd70382f0364429f6349800eeb68b1' \
  '/usr/local/sbin/arch-bootstrap'

execute_download \
  'https://raw.githubusercontent.com/novln/Kiss-my-Arch/master/bootstrap/intel-nuc-8i3beh-install/configure' \
  'b0d1af677cb3f6cdd2b21b43cb6bc21aacc7684125c512d90ec4ee7744912ffe' \
  '/usr/local/sbin/arch-configure'

timedatectl set-ntp true

/usr/local/sbin/arch-bootstrap
if [[ $? -ne 0 ]]; then
  exit 254
fi

exit 0
