---
- name: install Xorg
  tags: xorg
  pacman:
    name: "xorg-server,xorg-xinit"
    state: present
  register: xorg_install

- name: install Xorg input drivers for laptop
  tags: xorg
  pacman:
    name: "xf86-input-libinput,xf86-input-mouse,xf86-input-keyboard"
    state: present
  when: xorg_desktop is undefined or xorg_desktop is false

- name: install Xorg input drivers for all
  tags: xorg
  pacman:
    name: "xsel,xclip"
    state: present

- name: install Xorg video drivers
  tags: xorg
  pacman:
    name: "xf86-video-intel,xf86-video-vesa"
    state: present

- name: write keyboard configuration for Xorg
  tags: xorg
  template:
    src: "keyboard-layout.conf.j2"
    dest: "{{ xorg_keyboard_conf_path }}"
    owner: root
    group: root
    mode: 0644

- name: write touchpad configuration for Xorg
  tags: xorg
  template:
    src: "touchpad-input.conf.j2"
    dest: "{{ xorg_touchpad_conf_path }}"
    owner: root
    group: root
    mode: 0644

- name: install X11 fonts with pacman (this may take a while)
  tags: fonts
  pacman:
    name:
      - cantarell-fonts
      - fontconfig
      - freetype2
      - gsfonts
      - sdl_ttf
      - sdl2_ttf
      - ttf-bitstream-vera
      - ttf-dejavu
      - gnu-free-fonts
      - ttf-hack
      - ttf-croscore
      - ttf-sazanami
      - ttf-hannom
      - ttf-droid
      - ttf-fira-mono
      - ttf-fira-code
      - ttf-fira-sans
      - ttf-hanazono
      - ttf-cormorant
      - ttf-baekmuk
      - otf-cormorant
      - otf-ipafont
      - otf-font-awesome
      - powerline-fonts
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
      - noto-fonts-extra
      - adobe-source-code-pro-fonts
      - adobe-source-sans-pro-fonts
      - adobe-source-serif-pro-fonts
      - adobe-source-han-sans-otc-fonts
      - adobe-source-han-sans-kr-fonts
      - adobe-source-han-sans-jp-fonts
      - adobe-source-han-sans-cn-fonts
      - adobe-source-han-sans-tw-fonts
      - adobe-source-han-serif-cn-fonts
      - adobe-source-han-serif-jp-fonts
      - adobe-source-han-serif-kr-fonts
      - adobe-source-han-serif-otc-fonts
      - adobe-source-han-serif-tw-fonts
      - ttf-arphic-ukai
      - ttf-arphic-uming
      - opendesktop-fonts
      - wqy-microhei
      - wqy-zenhei
      - wqy-bitmapfont
      - ttf-liberation
      - ttf-ubuntu-font-family
      - xorg-fonts-type1
      - ttf-ionicons
      - ttf-carlito
      - ttf-linux-libertine
    state: present