---
- include: archlinux.yml
- include: time.yml
- include: pacman.yml
- include: hostname.yml
- include: bash.yml
- include: zsh.yml
- include: user.yml
- include: kernel.yml
- include: ssh.yml
- include: network.yml
- include: spelling.yml
