---
- name: install dhclient with pacman
  tags: network
  pacman:
    name: "dhclient"
    state: present

- name: configure dhclient for NetworkManager
  tags: network
  template:
    src: dhcp-client.conf.j2
    dest: /etc/NetworkManager/conf.d/dhcp-client.conf
    owner: root
    group: root
    mode: 0644

- name: install iwd with pacman
  tags: network
  pacman:
    name: "iwd"
    state: present

- name: enable iwd at startup
  tags: network
  service:
    name: "iwd"
    enabled: yes

- name: configure iwd for NetworkManager
  tags: network
  template:
    src: wifi-backend.conf.j2
    dest: /etc/NetworkManager/conf.d/wifi-backend.conf
    owner: root
    group: root
    mode: 0644
