#!/bin/bash

function execute_download() {
  declare file_url="$1" file_sha256sum="$2" file_path="$3"

  echo "[installer] download ${file_url}"
  wget "${file_url}" -O "${file_path}" || exit 255s
  chmod +x "${file_path}" || exit 255

  echo "${file_sha256sum} ${file_path}" | sha256sum -c - >/dev/null 2>&1
  if [[ $? -ne 0 ]]; then
    echo >&2 "Checksum verification failed for ${file_path}."
    exit 255
  fi

}

execute_download \
  'https://raw.githubusercontent.com/november-eleven/Kiss-my-Arch/master/bootstrap/vbox-install/bootstrap' \
  '7d026de54226714eabf4e7d855a548cca1173e59e7929eadd51a5b6c60dfc4d9' \
  '/usr/local/sbin/arch-bootstrap'

execute_download \
  'https://raw.githubusercontent.com/november-eleven/Kiss-my-Arch/master/bootstrap/vbox-install/configure' \
  'd2d684656a0d956b41526130ca98f6aa2de5b3c39ef68a52942ab3d53558070e' \
  '/usr/local/sbin/arch-configure'

timedatectl set-ntp true

/usr/local/sbin/arch-bootstrap
if [[ $? -ne 0 ]]; then
  exit 254
fi

exit 0
